{{- if .Values.crds.install }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-crd-install
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-crd-install
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: kubectl-apply
          image: bitnami/kubectl:latest
          command:
            - kubectl
            - apply
            - -f
            - /crds/inspect.example.com_inspectsandboxes.yaml
          volumeMounts:
            - name: crds
              mountPath: /crds
      volumes:
        - name: crds
          configMap:
            name: {{ .Release.Name }}-crds
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-crds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
data:
  inspect.example.com_inspectsandboxes.yaml: |-
{{ .Files.Get "crds/inspect.example.com_inspectsandboxes.yaml" | indent 4 }}
{{- end }}