# Default values for inspect-sandbox-operator

# Deployment configuration
deployment:
  replicas: 1
  image:
    repository: ghcr.io/tomcatling/inspect-sandbox-operator
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# RBAC settings
rbac:
  create: true

# ServiceAccount settings
serviceAccount:
  create: true
  name: "inspect-operator"

# CRD settings
crds:
  install: true