apiVersion: v1
kind: Namespace
metadata:
  name: inspect-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inspect-operator
  namespace: inspect-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: inspect-operator-role
rules:
- apiGroups: ["inspect.example.com"]
  resources: ["inspectsandboxes", "inspectsandboxes/status", "inspectsandboxes/finalizers"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["services", "configmaps", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumnetworkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: inspect-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: inspect-operator-role
subjects:
- kind: ServiceAccount
  name: inspect-operator
  namespace: inspect-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inspect-operator
  namespace: inspect-system
  labels:
    app.kubernetes.io/name: inspect-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: inspect-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: inspect-operator
    spec:
      serviceAccountName: inspect-operator
      containers:
      - name: manager
        image: ghcr.io/tomcatling/inspect-sandbox-provider:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10