apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inspectsandboxes.inspect.example.com
spec:
  group: inspect.example.com
  names:
    kind: InspectSandbox
    listKind: InspectSandboxList
    plural: inspectsandboxes
    singular: inspectsandbox
    shortNames:
      - isbox
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                services:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      image:
                        type: string
                      runtimeClassName:
                        type: string
                      command:
                        type: array
                        items:
                          type: string
                      args:
                        type: array
                        items:
                          type: string
                      workingDir:
                        type: string
                      dnsRecord:
                        type: boolean
                      additionalDnsRecords:
                        type: array
                        items:
                          type: string
                      env:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      volumes:
                        type: array
                        items:
                          type: string
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            additionalProperties:
                              type: string
                          requests:
                            type: object
                            additionalProperties:
                              type: string
                      networks:
                        type: array
                        items:
                          type: string
                allowDomains:
                  type: array
                  items:
                    type: string
                networks:
                  type: object
                  additionalProperties:
                    type: string
                volumes:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      size:
                        type: string
                      storageClass:
                        type: string
            status:
              type: object
              properties:
                conditions:
                  type: array
                  items:
                    type: object
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      observedGeneration:
                        type: integer
                        format: int64
                      lastTransitionTime:
                        type: string
                        format: date-time
                      reason:
                        type: string
                      message:
                        type: string
                services:
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      ready:
                        type: boolean
                      message:
                        type: string
      additionalPrinterColumns:
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
      - name: Status
        type: string
        jsonPath: .status.conditions[?(@.type=="Ready")].status