name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Setup Helm Chart Repository
        run: |
          # Create required directories
          mkdir -p .cr-release-packages
          
          # Package the chart
          helm package charts/inspect-sandbox-operator -d .cr-release-packages
          
          # Check if helm-release branch exists
          if git ls-remote --heads origin helm-release | grep -q 'refs/heads/helm-release'; then
            # If it exists, check it out
            git checkout helm-release
          else
            # If it doesn't exist, create a new orphan branch
            git checkout --orphan helm-release
            git reset --hard
            rm -rf *
            # Create an empty index.yaml to start with
            touch index.yaml
            git add index.yaml
            git commit -m "Initialize helm-release branch"
          fi
          
          # Move the packaged chart to the current directory
          cp .cr-release-packages/*.tgz .
          
          # Merge the new chart into the existing index or create a new one if it doesn't exist
          if [ -f "index.yaml" ]; then
            helm repo index --url https://tomcatling.github.io/inspect-sandbox-operator/ --merge index.yaml .
          else
            helm repo index --url https://tomcatling.github.io/inspect-sandbox-operator/ .
          fi
          
          # Commit changes
          git add .
          git commit -m "Publish Helm chart $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Push updates to helm-release branch
          git push origin helm-release