name: Release Helm Charts

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm-release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0

      - name: Setup Helm Chart Repository
        run: |
          # Package the chart
          helm package charts/inspect-sandbox-operator -d /tmp
          
          # Check if helm-releases branch exists
          if git ls-remote --heads origin helm-releases | grep -q 'refs/heads/helm-releases'; then
            # If it exists, check it out
            git checkout helm-releases
          else
            # If it doesn't exist, create a new orphan branch
            git checkout --orphan helm-releases
            git reset --hard
            rm -rf *
          fi
          
          # Move the packaged chart to the current directory
          cp /tmp/*.tgz .
          
          # Generate the index file (create new or merge with existing)
          if [ -f "index.yaml" ]; then
            helm repo index --url https://tomcatling.github.io/inspect-sandbox-operator/ --merge index.yaml .
          else
            helm repo index --url https://tomcatling.github.io/inspect-sandbox-operator/ .
          fi
          
          # Commit changes
          git add .
          git commit -m "Publish Helm chart $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          
          # Push changes to helm-releases branch (not force push)
          git push origin helm-releases